### ISSUE TITLE
Idaho's "positive" started including presumed cases 4/17, so possibly off by up to 9.8% as of 5/17

### ISSUE THREAD

**Issue by waded** [COVID19Tracking/issues#308]
The report for Idaho at https://covidtracking.com/data as of 4/26 states "as of 4/24, Idaho separately reports both probable and confirmed cases". That's not correct; Idaho DHW started reporting probable cases separately from confirmed (positive) cases on 4/9, and the number of cases shown on https://coronavirus.idaho.gov since 4/17 has been the **sum** of probable and confirmed/positive!

At the time I opened this issue the API documents stated "positive" is "Total cumulative positive test results", so I presume the data you're collecting as "positive" wasn't intended to include Idaho's probable counts.

You can see evidence of this in [screencaps](https://covidtracking.com/data/state/idaho#historical). Note the label, and what the label says going back through 4/17, 4/9, earlier.

![image](https://user-images.githubusercontent.com/1535656/80336420-701e9f80-8814-11ea-9773-567cd25810c1.png)

Idaho DHW's Tableau dashboard (which https://coronavirus.idaho.gov started linking to on 4/2) has the detailed data needed to fix this, in tooltips on this cumulative cases chart:

![image](https://user-images.githubusercontent.com/1535656/80322438-73993300-87e2-11ea-9b82-0ff88c9ae68c.png)

If the chart is ever removed, I have a copy of the data as far back as 4/9 I can provide.

**Comment by waded** [comment]
The link for the state's Tableau dashboard that the correct lab-confirmed counts is currently https://public.tableau.com/profile/idaho.division.of.public.health#!/vizhome/DPHIdahoCOVID-19Dashboard_V2/Story1

(That URL's changed at least once since they started publishing it. They've to-date always linked to it from https://coronavirus.idaho.gov.)

**Comment by waded** [comment]
This is still an issue. For example, Idaho DHW reported 2203 cumulative confirmed/positive, 216 cumulative probable on 5/16, for a sum of 2419 (the sum is published at coronavirus.idaho.gov, the detail is published on the Tableau dashboard linked to from there, daily just after 5PM Mountain, except now on Sunday.) 

It appears the project has captured positive=2419 for date=2020517.

Idaho DHW's not explained how these counts handle probables that become positive, but I will say that since there have been days when the probable cumulative count decreased (5/7 for example), so I think what they are doing is subtracting probable and adding them to confirmed. That indicates this project may be overcounting Idaho positives by up to 216/2203=9.8% as of 5/16.

**Comment by waded** [comment]
Let me know how I can help here. I've developed a Tableau extract parawr that can get the correct numbers from Idaho DHW's dashboard, but I don't quite understand the layout of this project, in particular how the scraping works for Idaho now.

**Comment by karaschechtman** [comment]
Hi @waded,
Thanks for bringing this to our attention. We are currently reviewing the issue and should have updates for you shortly.
(Next github issues shift: for comments see https://covid-tracking.slack.com/archives/C0116LT5CTT/p1589985879306600)

**Comment by karaschechtman** [comment]
Hi @waded,
Thanks for pointing out this data. It was not a problem for positive count since we bundle confirmed and probable cases for that field. However, it turned out that we had sometimes been inferring our negative test counts with total - (confirmed + probable) negatives, rather than total - confirmed, before we made a note of Idaho's separation of the fields formally. As a result, many of our negative test values were too low. 

I went through our edit history for negatives, and located days we calculated the negative value using confirmed + probable positives according to the figures from hovering over each day on the Tableau chart "[Statewide cases](https://public.tableau.com/profile/idaho.division.of.public.health#!/vizhome/DPHIdahoCOVID-19Dashboard_V2/Story1)". Then I corrected those days to subtract just the confirmed positives (those that had been verified by tests) from totals rather than confirmed + probables. Note that, depending on the time of day we updated, there was sometimes a 1-day lag I had to account for. There were 12 days between 4/16-4/30 I corrected. I also carried over a negative value on one day to prevent decreases in negatives.


After:
<img width="262" alt="Screen Shot 2020-05-21 at 9 50 16 AM" src="https://user-images.githubusercontent.com/15933271/82565871-1d04e780-9b49-11ea-864d-0a46d3f546d4.png">


Before:

April 30
￼<img width="239" alt="Pasted Graphic 2" src="https://user-images.githubusercontent.com/15933271/82566192-8be24080-9b49-11ea-9ccc-4dc89a0cdc4f.png">
Should be 1831 (from April 29): 28693-1831 = 26862



April 27
￼<img width="236" alt="Pasted Graphic 3" src="https://user-images.githubusercontent.com/15933271/82566229-98ff2f80-9b49-11ea-976d-b4468145b201.png">
Should be 1768 (from April 26): 19895-1768=18127

April 26
<img width="237" alt="Pasted Graphic 4" src="https://user-images.githubusercontent.com/15933271/82566245-9e5c7a00-9b49-11ea-8e8c-afcbe97f6f6c.png">
Should be 1760 (from April 25): 19361-1760=17601. But, carried 17611 to not decrease negatives.

(Note: changed April 25 in our data to 17611 to account for removal of evening shift & not decrease negatives)

April 24
<img width="235" alt="Pasted Graphic 5" src="https://user-images.githubusercontent.com/15933271/82566272-a9170f00-9b49-11ea-82a2-d8c5ba3de786.png">
Should be 1750 (from April 24): 19361-1750=17611. 


April 23
<img width="235" alt="Pasted Graphic 6" src="https://user-images.githubusercontent.com/15933271/82566309-b633fe00-9b49-11ea-9a7a-a0a408d8df05.png">
Should be 1721 (from April 23): 19091-1721=17370

April 22
<img width="238" alt="Pasted Graphic 7" src="https://user-images.githubusercontent.com/15933271/82566328-baf8b200-9b49-11ea-81db-42ea6e7d8372.png">
Should be 1688 (from April 22): 18092-1688=16404


April 21
￼<img width="233" alt="Pasted Graphic 8" src="https://user-images.githubusercontent.com/15933271/82566341-c2b85680-9b49-11ea-8d10-284653532a63.png">
Should be 1659 (from April 21): 17730-1659=16071


April 19
￼<img width="230" alt="Pasted Graphic 10" src="https://user-images.githubusercontent.com/15933271/82566354-c9df6480-9b49-11ea-98f1-8b678d6b43c5.png">
Should be 1581 (from April 19): 17445-1672=15773

April 18
￼<img width="234" alt="Pasted Graphic 11" src="https://user-images.githubusercontent.com/15933271/82566369-d19f0900-9b49-11ea-9c7d-f529f17ed736.png">
Should be 1577 (from April 18): 16869-1577=15292

April 17
￼<img width="238" alt="Pasted Graphic 12" src="https://user-images.githubusercontent.com/15933271/82566385-d6fc5380-9b49-11ea-93f3-6fd30b28650e.png">
Should be 1566 (from April 17): 16609-1566=15043


April 16
<img width="244" alt="Pasted Graphic 13" src="https://user-images.githubusercontent.com/15933271/82566403-debbf800-9b49-11ea-924b-3d21dc16e4a7.png">
Should be 1528 (from April 16): 16183-1528=14655

We will change our public note to reflect that ID has been reporting confirmed positives since 4/9.

**Comment by waded** [comment]
I'll check back in a few days when this is flushed through and e.g. 5/22's numbers can be observed to 

I still don't agree that Idaho's "probable" count should be bundled into "positives", which in API docs still describe simply as "Total cumulative positive test results" and Idaho's "probables" are not that. But if that is intentional and you're doing it consistently across states, then so be it (although I recommend API docs be more specific; I will open a separate issue.)
